// GENERATED BY ELICIT - DO NOT EDIT

package specs_test

import (
	"mmatt/elicit"
	steps "mmatt/elicit/examples/fibonacci/steps"
)

func init() {
	e := elicit.CurrentContext

	e.RegisterStep("Step to run (before|after) each scenario", steps.StepToRunPhaseEachScenario)
	e.RegisterStep("The (.*) and the (.*)", steps.StepWithMismatchedPattern)
	e.RegisterStep("The first (\\d+) items are ((?:\\d+,\\s*)+\\d+)", steps.TheFirstNItemsAreX)
	e.RegisterStep("The (-?\\d+)(?:st|nd|rd|th) to the (-?\\d+)(?:st|nd|rd|th) items are ((?:-?\\d+,\\s*)+-?\\d+)", steps.TheFoothToTheBarthItemsAreBaz)
	e.RegisterStep("The (-?\\d+)(?:st|nd|rd|th) item is (-?\\d+)", steps.TheNthItemIsX)
	e.RegisterStep("This step takes a table parameter", steps.ThisStepTakesATableParameter)
}
