// GENERATED BY ELICIT - DO NOT EDIT

package specs_test

import (
	"mmatt/elicit"
	"testing"
)

func Test_Example_Sub_Spec(t *testing.T) {
	e := elicit.CurrentContext

	e.BeginSpecTest("Example Sub Spec")

	t.Run("A Scenario", func(t *testing.T) {
		e.BeginScenarioTest("A Scenario")

		e.RunStep("Something Here")

		e.RunStep("Test Step 1")
		e.RunStep("Test Step 2")

		if r, l := e.EndScenarioTest(); r == elicit.Failed {
			t.Errorf(l)
		} else if r == elicit.Skipped {
			t.Skipf(l)
		}
	})
}
